### ISSUE TITLE
4 switch dataset

### ISSUE THREAD

**Issue by Cheny-chui** [delta-net/datasets#3]
Hello, the dataset in kaggle doesn't seem to have 4switch file, how should I get it. Thanks

**Comment by kheradmand** [comment]
Hi Cheni-chui, this dataset is not maintained anymore. I might or might not have the data on an old hard drive. If I find it, I will let you know.

**Comment by kheradmand** [comment]
Hi again, unfortunately I no longer have the data. Other researchers may still have it. I suggest contacting the authors of any other paper that has reported on experiments using the 4switch data.

**Comment by Cheny-chui** [comment]
Hi kheradmand, thank you for your response, I will try to contact other researchers who use this dataset.
